// src/context/appState/initialState.js

export const initialAppState = {
  startingWeight: 0, currentWeight: 0, totalWorkoutsCompleted: 0,
  weightHistory: [], photos: [], beforePhoto: null, afterPhoto: null, totalLbsLifted: 0, totalReps: 0, totalSets: 0,
  totalCardioMinutes: 0,
  programs: [],
  workoutSchedule: {},
  viewingDate: new Date().toISOString().split('T')[0],
  viewingScheduleId: null,
  oneRepMaxes: {},
  unitSystem: 'imperial',
  isModalOpen: false, modalContent: null, showConfetti: false,
  isWorkoutEditorOpen: false, editingInfo: null,
  workoutToScheduleId: null,
  isInfoModalOpen: false,
  infoModalContent: null,
  isPremium: false,
  isPremiumModalOpen: false,
  stripeCustomerId: null,
  subscriptionId: null,
  subscriptionStatus: null,
  subscriptionPriceId: null,
  subscriptionCurrentPeriodEnd: null,
  subscriptionCancelAtPeriodEnd: false,
  subscriptionEndDate: null,
  username: null,
  friends: [],
  friendRequestsSent: [],
  friendRequestsReceived: [],
  customExercises: [],
  pendingExerciseEditId: null,
};